import type {
  GenerateLlmsFullTxtOptions,
  GenerateLlmsTxtOptions,
} from './types';
import { scanAppDirForPages } from './scan';

function isoNow(): string {
  return new Date().toISOString();
}

function groupHeadingForRoute(routePath: string): string {
  const seg = routePath.split('/').filter(Boolean)[0];
  if (!seg) return 'Home';
  return seg.replace(/[-_]+/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

function stripHtmlToText(html: string): string {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/<style[\s\S]*?<\/style>/gi, '')
    .replace(/<\/(p|div|section|article|h\d|li|ul|ol|br)\s*>/gi, '\n')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/[ \t]+\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function extractHtmlTitle(html: string): string {
  const m = /<title[^>]*>([^<]+)<\/title>/i.exec(html);
  if (!m) return '';
  return m[1]
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .trim();
}

async function fetchWithTimeout(
  url: string,
  timeoutMs: number
): Promise<string> {
  if (typeof fetch !== 'function') {
    throw new Error(
      'Global fetch() is not available. Use Node.js >= 18 or provide a fetch polyfill.'
    );
  }
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, {
      signal: controller.signal,
      headers: { 'User-Agent': '@llmtxt/core' },
    });
    if (!res.ok)
      throw new Error(
        `Fetch failed for ${url}: ${res.status} ${res.statusText}`
      );
    return await res.text();
  } finally {
    clearTimeout(timeout);
  }
}

export async function generateLlmsTxt(
  options: GenerateLlmsTxtOptions
): Promise<string> {
  const title = options.title ?? 'Documentation';
  const pages = await scanAppDirForPages(options);

  const byGroup = new Map<string, typeof pages>();
  for (const page of pages) {
    const group = groupHeadingForRoute(page.routePath);
    byGroup.set(group, [...(byGroup.get(group) ?? []), page]);
  }

  const lines: string[] = [];
  lines.push(`# ${title}`);
  if (options.summary) {
    lines.push('');
    lines.push(`> ${options.summary}`);
  }
  lines.push('');

  for (const [group, groupPages] of [...byGroup.entries()].sort((a, b) =>
    a[0].localeCompare(b[0])
  )) {
    lines.push(`## ${group}`);
    lines.push('');
    for (const page of groupPages) {
      const suffix = page.description ? `: ${page.description}` : '';
      lines.push(`- [${page.title}](${page.url})${suffix}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(
    `*Generated by @llmtxt/core · ${isoNow()} · ${pages.length} pages*`
  );
  lines.push('');
  return lines.join('\n');
}

export async function generateLlmsFullTxt(
  options: GenerateLlmsFullTxtOptions
): Promise<string> {
  const pages = await scanAppDirForPages(options);
  const fetchTimeoutMs = options.fetchTimeoutMs ?? 5000;

  const lines: string[] = [];
  lines.push('# llms-full.txt');
  lines.push('');
  lines.push(
    `*Generated by @llmtxt/core · ${isoNow()} · ${pages.length} pages*`
  );
  lines.push('');
  lines.push('---');
  lines.push('');

  for (const page of pages) {
    lines.push(`## ${page.title}`);
    lines.push('');
    lines.push(`title: ${page.title}`);
    lines.push(`url: ${page.url}`);
    if (page.description) lines.push(`description: ${page.description}`);
    try {
      const html = await fetchWithTimeout(page.url, fetchTimeoutMs);
      const htmlTitle = extractHtmlTitle(html);
      if (htmlTitle) lines.push(`page title: ${htmlTitle}`);
      lines.push('');
      const markdown =
        typeof options.htmlToMarkdown === 'function'
          ? await options.htmlToMarkdown(html, page.url)
          : stripHtmlToText(html);
      lines.push(markdown.trim());
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      lines.push(`(Failed to fetch or convert content: ${msg})`);
    }
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  return lines.join('\n');
}
