import fs from 'fs/promises';
import path from 'path';
export { scanPagesDirForRoutes } from './scan';
export type { ScanPagesDirOptions } from './scan';

export type LlmtxtRoute = {
  path: string;
  title: string;
  description?: string;
  /**
   * Optional precomputed Markdown for this route.
   * If provided, `llms-full.txt` uses this instead of fetching HTML.
   */
  markdown?: string;
};

export type WriteLlmsFilesOptions = {
  routes: LlmtxtRoute[];
  baseUrl: string;
  outDir: string;
  fetchTimeoutMs?: number;
  htmlToMarkdown?: (html: string, url: string) => Promise<string> | string;
  /**
   * Optional fetcher for HTML. Use this to support SPAs/dynamic pages by
   * rendering with a headless browser (Playwright/Puppeteer) instead of plain fetch.
   */
  fetchHtml?: (url: string, timeoutMs: number) => Promise<string>;
  title?: string;
  summary?: string;
};

function normalizeBaseUrl(baseUrl: string): string {
  return baseUrl.replace(/\/+$/, '');
}

function isoNow(): string {
  return new Date().toISOString();
}

function stripHtmlToText(html: string): string {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/<style[\s\S]*?<\/style>/gi, '')
    .replace(/<\/(p|div|section|article|h\d|li|ul|ol|br)\s*>/gi, '\n')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/[ \t]+\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function looksLikeClientRenderedSpa(html: string, markdown: string): boolean {
  const hasLikelyMount =
    /<div[^>]+id=["']root["'][^>]*><\/div>/i.test(html) ||
    /<div[^>]+id=["']app["'][^>]*><\/div>/i.test(html);
  const hasScripts = /<script\b/i.test(html);
  const words = markdown.trim().split(/\s+/).filter(Boolean);
  return hasLikelyMount && hasScripts && words.length <= 6;
}

async function fetchWithTimeout(url: string, timeoutMs: number): Promise<string> {
  if (typeof fetch !== 'function') {
    throw new Error(
      'Global fetch() is not available. Use Node.js >= 18 or provide a fetch polyfill.'
    );
  }
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, {
      signal: controller.signal,
      headers: { 'User-Agent': '@llmtxt/react' },
    });
    if (!res.ok) {
      throw new Error(`Fetch failed for ${url}: ${res.status} ${res.statusText}`);
    }
    return await res.text();
  } finally {
    clearTimeout(timeout);
  }
}

export async function generateLlmsTxtFromRoutes(options: {
  routes: LlmtxtRoute[];
  baseUrl: string;
  title?: string;
  summary?: string;
}): Promise<string> {
  const title = options.title ?? 'Documentation';
  const baseUrl = normalizeBaseUrl(options.baseUrl);
  const routes = [...options.routes].sort((a, b) => a.path.localeCompare(b.path));

  const lines: string[] = [];
  lines.push(`# ${title}`);
  if (options.summary) {
    lines.push('');
    lines.push(`> ${options.summary}`);
  }
  lines.push('');

  for (const route of routes) {
    const url = `${baseUrl}${route.path === '/' ? '' : route.path}`;
    const suffix = route.description ? `: ${route.description}` : '';
    lines.push(`- [${route.title}](${url})${suffix}`);
  }

  lines.push('');
  lines.push('---');
  lines.push(`*Generated by @llmtxt/react · ${isoNow()} · ${routes.length} pages*`);
  lines.push('');
  return lines.join('\n');
}

export async function generateLlmsFullTxtFromRoutes(options: {
  routes: LlmtxtRoute[];
  baseUrl: string;
  fetchTimeoutMs?: number;
  htmlToMarkdown?: (html: string, url: string) => Promise<string> | string;
  fetchHtml?: (url: string, timeoutMs: number) => Promise<string>;
}): Promise<string> {
  const baseUrl = normalizeBaseUrl(options.baseUrl);
  const routes = [...options.routes].sort((a, b) => a.path.localeCompare(b.path));
  const fetchTimeoutMs = options.fetchTimeoutMs ?? 8000;

  const lines: string[] = [];
  lines.push('# llms-full.txt');
  lines.push('');
  lines.push(`*Generated by @llmtxt/react · ${isoNow()} · ${routes.length} pages*`);
  lines.push('');
  lines.push('---');
  lines.push('');

  for (const route of routes) {
    const url = `${baseUrl}${route.path === '/' ? '' : route.path}`;
    lines.push(`## ${route.title}`);
    lines.push('');
    lines.push(url);
    lines.push('');
    try {
      if (route.markdown) {
        lines.push(route.markdown.trim());
      } else {
        const html =
          typeof options.fetchHtml === 'function'
            ? await options.fetchHtml(url, fetchTimeoutMs)
            : await fetchWithTimeout(url, fetchTimeoutMs);
        const markdown =
          typeof options.htmlToMarkdown === 'function'
            ? await options.htmlToMarkdown(html, url)
            : stripHtmlToText(html);
        const trimmed = markdown.trim();
        lines.push(trimmed);
        if (looksLikeClientRenderedSpa(html, trimmed)) {
          lines.push('');
          lines.push(
            '(Note: This route looks like a client-rendered SPA shell. For full content, provide `route.markdown`, prerender/SSR HTML, or pass `fetchHtml` to render with a headless browser.)'
          );
        }
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      lines.push(`(Failed to fetch or convert content: ${msg})`);
    }
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  return lines.join('\n');
}

export async function writeLlmsFiles(options: WriteLlmsFilesOptions): Promise<{
  llmsTxtPath: string;
  llmsFullTxtPath: string;
}> {
  const outDir = path.resolve(options.outDir);
  await fs.mkdir(outDir, { recursive: true });

  const llmsTxt = await generateLlmsTxtFromRoutes({
    routes: options.routes,
    baseUrl: options.baseUrl,
    title: options.title,
    summary: options.summary,
  });
  const llmsFullTxt = await generateLlmsFullTxtFromRoutes({
    routes: options.routes,
    baseUrl: options.baseUrl,
    fetchTimeoutMs: options.fetchTimeoutMs,
    htmlToMarkdown: options.htmlToMarkdown,
    fetchHtml: options.fetchHtml,
  });

  const llmsTxtPath = path.join(outDir, 'llms.txt');
  const llmsFullTxtPath = path.join(outDir, 'llms-full.txt');
  await fs.writeFile(llmsTxtPath, llmsTxt, 'utf8');
  await fs.writeFile(llmsFullTxtPath, llmsFullTxt, 'utf8');

  return { llmsTxtPath, llmsFullTxtPath };
}
